variable "resource_group_name" {}
variable "location" {}
variable "virtual_network_name" {}
variable "virtual_network_cidr" {}
variable "subnet_name" {}
variable "subnet_cidr" {}
variable "virtual_machine_name" {}
variable "admin_username" {}
variable "admin_password" {}